[package]
name = "set_lang"
version = "0.1.0"
edition = "2018"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2.14"
educe = "0.4.18"
itertools = "0.10.1"

